### PR TITLE
Factor out C wrappers in separate Cython modules.

### PR DESCRIPTION
**Pull request by Flameeyes**
This request is a bit complicated and huge, but I'm sending it on the grounds of:

 * the current PYSCSI build on PyPI is not Python 3 compatible at all, and is thus unusable;
 * the git build would work, but it's still overly complicated;
 * Python packaging is moving on from distutils, and the current extension selection is going to break eventually.

Using Cython allows moving some of the wrapping logic close to the wrapped interfaces, and avoids the dependency on SWIG, make and so on.

To make things easier to maintain, the Cython wrappers are split on their own PyPI packages and repositories:

 * [cython-iscsi](https://github.com/python-scsi/cython-iscsi) (unreleased);
 * [cython-sgio](https://github.com/python-scsi/cython-sgio) (https://pypi.org/project/cython-sgio/).

While at it, make use of Python 3 feature (and mark the library as requiring Python 3.7), including but not limited to:

 * no need for future imports;
 * new metaclass syntax;
 * type annotations (with mypy).

Also, give a blueprint for moving the tests to unittests, which will make continuous integration easier to set up.

### CODE REVIEW

**Comment by rosjat** [comment]
Hey diego,

Appreciate the work it's a lot to review but for the sake of it I would
like to make it a python 3 branch so we have it there and if problems show
up we can work from there. To be honest I didn't spend to much time with
cpython so I might need a while to catch up with it but moving to pipy is a
sane move since lol are looking for a simple way to install it anyway. I am
at a plane right now but when I am back home I will set up stuff so we can
pull it in a new branch or even in a new pthon3 repo.

Regards

Markus

Diego Elio Pettenò <notifications@github.com> schrieb am Di., 24. März
2020, 09:59:

**Comment by Flameeyes** [comment]
No hurry from me, I just wanted to put something out there first, I'm still hammering out at a few kinks around the edges on this, and I might take some time to move the tests to work with pytest later.

FWIW this _should_ work fine on both Py2 and Py3 as it is, but I don't even have an install of Py2 to test this on right now.

**Comment by rosjat** [comment]
World is moving away from py2 anyway so it's overdue to revisit some stuff.
Even the C code will work it's ok for me to go down a road that supports
pipy since lol tend to use it and it's faster for beginners anyway. Py3
will be the way to go and I looked into type annotations as well, what
keeps me a little reluctant is the definition of types we need to do to
just get type checkers to work with it  ;) anyway I was going back and
forth on py3 the last 2 years but there was never really a reason till now.
Anyway py3 has lots of cool stuff and it's worth to embrace it



Diego Elio Pettenò <notifications@github.com> schrieb am Di., 24. März
2020, 10:32:

**Comment by Flameeyes** [comment]
Okay so I started looking at how much Python 2 compatibility is around, and the answer is not much, but also a few places had non-Python 3 compatible calls.

The current pull request includes basic mypy hygiene, and it does indeed pass typing now.

I guess more things that could be done would be to use isort and black, but I think this is enough to review as is :)

**Comment by rosjat** [comment]
Yeah give me time, i need to work through it. But like i said before i like
the idea of a Python 3 branch or eben repo anyway

Diego Elio Pettenò <notifications@github.com> schrieb am Di., 24. März
2020, 15:04:

**Comment by Flameeyes** [comment]
Okay I ended up doing some work around this, and split the sgio wrapper on its own module and [repository](https://github.com/glucometers-tech/cython-sgio) — I added it to glucometers-tech because that's where the project I need this for, but I would be partial to creating a `python-scsi` org, and move it there, together with this, [cython-sgutils](https://github.com/glucometers-tech/cython-sgutils) (that turned out to be a dead end), and maybe a separate `cython-iscsi`.

What do you think?

**Comment by rosjat** [comment]
this sounds like a reasonable idea, so we can provide both ways and of accessing sgio. for a pipy version we could then just do your new module so at least ppl who want to try it out in an easy way can install it without hassle. So if you like to make a module just send a pull request when its done. Sorry for not responding but i came home from a trip on the weekend and need to settle in first, crazy times took me almost 1k km away from my planded arrival -.-

**Comment by Flameeyes** [comment]
Hah don't worry about the timing — I had a week of "staycation" to burn so I spent deep into glucometerutils and connected libraries, thus why I got to this. This is my last week at current job, and will be mostly free for six weeks after that :)

**Comment by rosjat** [comment]
yeah changed from ubuntu to fedora today so need a little more time to setup, I quit my job in january but it seems hard to get something going now. Still got a few c# things to maintain but I hope to spend a little more time with this repo too, still like the idea of a full python3 version ;) but enough shitchat  lets focus on the code ;)

**Comment by Flameeyes** [comment]
Okay — cython-iscsi is set up as well, and it has some basic testing that turned out to require some Travis CI configuration I didn't expect (newer Ubuntu build). Reflected in the README.md file of it as well.

Now two options:

 1. We close this pull request, I send you a different one that just uses the new modules, without Cython references in this repository at all.
 2. You merge the pull request once you feel satisfied with it, and the history is present here.

In either case, whenever you feel like it, you can also move this repository to the [python-scsi org](https://github.com/python-scsi) (Settings -> Transfer) and we can keep everything together there.

I set up [Mergify](https://mergify.io/) for the cython-* repositories, which means pull requests just need to be approved, and not break Travis CI, to be auto-merged to the repositories there, we can add that to python-scsi if you prefer as well.

**Comment by rosjat** [comment]
i would go for option 1 since its more clean and we might get something to work with both modules the old and the new. I like to keep the old code around since its not really breaking something and its a nice simple module (at least sgio). For libiscsi there might be no need after the merge since this was more of a "helper" to get things going with iscsi as well and there is a need for iscsi I am sure :)

**Comment by rosjat** [comment]
so i tested the patch and it looks okay for sgio so far, will do iscsi later tonight i guess but it should be ok since the only diffrence is the device access. What I will do is branch off the old way of doing stuff so the code isnt lost in the process. after that I will merge your code into master and we can take it from there. Whats to be checked is the lib path  see [https://github.com/python-scsi/cython-iscsi/issues/1](https://github.com/python-scsi/cython-iscsi/issues/1) but i guess thats not a big issue

**Comment by rosjat** [comment]
we resolved this with the #83  pull request

**Pull request closed without merging**
