### PR TITLE
Python 3 and mypy support.

### PR DESCRIPTION
**Pull request by Flameeyes**

### CODE REVIEW

**Comment by rosjat** [comment]
I need to take a look at this, but I dont think to scatter tests around is usefull. There should be one test folder and all test should live there. Also the ignore file isnt really a part of the package, its up to a user of the repository to maintain a ignore file.

**Comment by Flameeyes** [comment]
The ignore file needs to be in the repository — otherwise `git` does not consider it. It's a standard file for `git` to use. It also prevents those files to be commited by mistakes (`git add .` will ignore them there too.)

I can move that last change away. I think the tests should be within the source tree, that's a pretty common design with pytest: https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code. But it can be a separate change.

**Comment by rosjat** [comment]
> The ignore file needs to be in the repository — otherwise `git` does not consider it. It's a standard file for `git` to use. It also prevents those files to be commited by mistakes (`git add .` will ignore them there too.)

I get that but in the end its not really a part of the code, its a part of the tool thats used to maintain the code. 

> I can move that last change away. I think the tests should be within the source tree, that's a pretty common design with pytest: https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code. But it can be a separate change.

yeah i would like to keep the test outside the pyscsi code, in the end there can be a test package if needed. what we started with is meant to be stand alone tests and I guess we can implement this approach even with pytest. 

As you might noticed I dont use much of intergration tools so I am not really paying attention to it. When I used python in my job I usally do it for simple scripts  to get some stuff arround the os done. So bear with me if I am a little reluctant, its not because I dont like it is mostly because I am not used to it or simply need to get up to speed with it.

**Comment by Flameeyes** [comment]
> > The ignore file needs to be in the repository — otherwise `git` does not consider it. It's a standard file for `git` to use. It also prevents those files to be commited by mistakes (`git add .` will ignore them there too.)
> 
> I get that but in the end its not really a part of the code, its a part of the tool thats used to maintain the code.

I know it sounds strange, but I'm fairly sure by now it's not really something that can be easily changed — but for now I moved it away from this PR.

`.gitignore`, GitHub configs, Travis CI, Mergify, they all get configured as files within the repository. They don't get packaged, but they do have to be versioned with the rest.

> yeah i would like to keep the test outside the pyscsi code, in the end there can be a test package if needed. what we started with is meant to be stand alone tests and I guess we can implement this approach even with pytest.

We can, but probably not a good idea: a lot of tools allow using them in uncommon scenarios, but stretching them that way can be a higher maintenance cost, as they are not really tested on those.

I would recommend keeping tests _in the repository_ within the same structure as the code. They don't need to be packaged in PyPI or installed, of course.

> As you might noticed I dont use much of intergration tools so I am not really paying attention to it. When I used python in my job I usally do it for simple scripts to get some stuff arround the os done. So bear with me if I am a little reluctant, its not because I dont like it is mostly because I am not used to it or simply need to get up to speed with it.

Slowly and a bit of a time works for me ;) I've had to learn these myself in the past few months as I never released anything on PyPI before a few weeks ago!

**Comment by rosjat** [comment]
yeah ppl are so caught up in pypi these days but to be honest if its possible to make a release for it why not.

**Comment by rosjat** [comment]
I will merge it now since most of the stuff isnt really doing anything new, type checking is a neat thing to have but wont break stuff since we moved the code to python3 more or less anyway. We might need to make that more clear in the readme but we will see, if I get used to the pypi setup we can declare dependencies and requirements there anyway

**Pull request merged**
