### PR TITLE
Set up integration testing for python-scsi, and document development.

### PR DESCRIPTION
**Pull request by Flameeyes**
This includes Travis CI settings to run tests and mypy (for type checking), and the basis to include further integration such as [pre-commit](https://pre-commit.com/).

For completeness, this includes `.gitignore` again, since it is indeed part of repository, not code, but so would `.travis.yml`, and that one cannot be not committed to gain integration support.

The new `DEVELOPMENT.md` file includes some details of the setup, and will be extended as more integration is introduced.

### CODE REVIEW

**Comment by rosjat** [comment]
you really want to push this trough, well lets compromise then! I will take all the ini and . files in and you make a nice readme section that explains whats really needed for the actual package and whit is convinience or integration ;)

**Comment by rosjat** [comment]
what exactly is pytest doing if pyscsi isnt installed? does it somehow import things on the fly? if so make would work still as long as the package is installed. And the intent of the tests, at least for now, is to verify that installed coed is running  as expected. so what is the benefit here? Dont get me wrong I am ok with unittests  I simply want to understand why excluding tests

**Comment by Flameeyes** [comment]
> you really want to push this trough, well lets compromise then! I will take all the ini and . files in and you make a nice readme section that explains whats really needed for the actual package and whit is convinience or integration ;)

I've added a new file with the development information, which should make it easier to separate the concerns for users vs the concerns for the contributors.



> what exactly is pytest doing if pyscsi isnt installed? does it somehow import things on the fly?

It will update the python import path to allow importing the local repository code.

> if so make would work still as long as the package is installed.

`make` will not work because you can't import `from .mock_device` when running the script by itself. But I don't feel it's a big loss given you can just `pytest tests/test_enum.py` to run a single file. And `make` is nearly unheard of when it comes to Python testing —- `pytest` is the standard approach, and works cross-platform.

> And the intent of the tests, at least for now, is to verify that installed coed is running as expected. so what is the benefit here? 

The main reason is to make it easier to run the integration — in particular `mypy` didn't work right before this because it didn't know whether `tests/` was a package or not. Now it should work fine.

**Comment by rosjat** [comment]
yeah didnt really noticed the __init__.py file in Tests

**Comment by rosjat** [comment]
> > you really want to push this trough, well lets compromise then! I will take all the ini and . files in and you make a nice readme section that explains whats really needed for the actual package and whit is convinience or integration ;)
> 
> I've added a new file with the development information, which should make it easier to separate the concerns for users vs the concerns for the contributors.
> 

I was thinking more of a short overview what is package relevant and what not. I always try to look at if i was new to python. I want to get to understand the code not all the noise around it but if  I clone or download the files I get a lot of files that are not really related to the code that is doing the work. So thats why I am reluctant to these files but i understand they are useful for integration. We never really intended to go that far I guess, ronnie said if you like to do something in python try to make a package that supports scsi in a usable way. And we both are not usual python guys haha he is a c guys and i did c# at work so our code looked and looks more like c or c# but than again i got used to python and try to improve 

> > what exactly is pytest doing if pyscsi isnt installed? does it somehow import things on the fly?
> 
> It will update the python import path to allow importing the local repository code.
> 
> > if so make would work still as long as the package is installed.
> 
> `make` will not work because you can't import `from .mock_device` when running the script by itself. But I don't feel it's a big loss given you can just `pytest tests/test_enum.py` to run a single file. And `make` is nearly unheard of when it comes to Python testing —- `pytest` is the standard approach, and works cross-platform.
> 
> > And the intent of the tests, at least for now, is to verify that installed coed is running as expected. so what is the benefit here?
> 
> The main reason is to make it easier to run the integration — in particular `mypy` didn't work right before this because it didn't know whether `tests/` was a package or not. Now it should work fine.

**Comment by Flameeyes** [comment]
Added a "repository layout" section — although that's pretty much the standard for a git repository.

Most Python libraries are rarely downloaded as an archive, rather installed with pip.

**Pull request merged**
