### PR TITLE
Add support for SYNCHRONIZE CACHE (10) and (16)

### PR DESCRIPTION
**Pull request by bmeagherix**
Add support for `SYNCHRONIZE CACHE (10)` and `SYNCHRONIZE CACHE (16)` as described in SBC-4
-  5.33 SYNCHRONIZE CACHE (10) command
-  5.34 SYNCHRONIZE CACHE (16) command

Tests are included.

### CODE REVIEW

**Comment by bmeagherix** [comment]
This PR failed a black formatting check for a file that was **not** being modified in this PR.  Therefore have created a separate PR (#139) to address that issue.

**Comment by rosjat** [comment]
@bmeagherix will take a look later, you might wanna update the PR to reflect the black changes I pulled from you fix

**Comment by bmeagherix** [comment]
@rosjat Thanks!  Have now updated PR => clean checks.

**Comment by rosjat** [comment]
sorry for the delay but I'm pretty busy at the moment. PR looks good to me

**Comment by bmeagherix** [comment]
> sorry for the delay but I'm pretty busy at the moment. PR looks good to me

Thank you!

**Pull request merged**
