### PR TITLE
Use buffering=0 for local device

### PR DESCRIPTION
**Pull request by phako**
Fixes an issue when opening the device read/write:

io.UnsupportedOperation: File or stream is not seekable.

### CODE REVIEW

**Comment by rosjat** [comment]
@phako I get the reason to set the buffering there but I dont think its a good way to do it as a default this way. In genral I would leave the buffering on and make it an option to to switch it off. 

so in my opinion, to not break it for older version, we could add a key word arg in __init__ with a default  that leaves buffering in place. So someone who wants no buffering can pass it in and it gets set in the open () method.

@sahlberg and @Flameeyes  might can give there 5 cent about it too

**Comment by phako** [comment]
What I understood from https://bugs.python.org/issue20074 is writing cannot work without specifying buffering=0 but maybe I got that wrong?

**Comment by rosjat** [comment]
this bug seems to apply to linux yes, and it seems not to be fixed but as I said before just because its something that doesnt work as expected we shouldnt make changes that restrict us from control it. So I would go for the suggested approach and in the end it wont break our code and still give ppl the ability to change it later on if this issue by python gets resolved in the future.

**Comment by phako** [comment]
Apologies, somewhat got distracted, will provide updated patch later today

**Comment by rosjat** [comment]
@phako thanks for the contribution, could update the doc strings too please so it refelects your changes made to the args.

cheers

Markus

**Comment by phako** [comment]
The code is wrong - while looking at the documentation the implementation now sets the buffer to 1 byte which is probably also not what you want. Will come back with a better solution

**Pull request merged**
